---
title: '20200915'
author: "QZ"
date: "9/17/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(printr)
theme_set(theme_classic())
```
load data
```{r Load data}
tt <- tt_load("2020-09-15")
tt
kids <- tt$kids
```

check how many factors in one column
```{r}
kids %>% 
  distinct(variable) %>% 
  count()
```

To check how PK12ed changes over the years in whole America
```{r}
kids %>% 
  filter(variable == "PK12ed") %>% 
  group_by(year) %>% 
  summarise(total = sum(inf_adj)) %>% 
  ggplot(aes(year, total)) +
  geom_line()+
  expand_limits(y = 0)+
  scale_y_continuous(labels = dollar)
```

to check 4 states in one graph
```{r}
kids %>%
  filter(variable == "PK12ed",
         state %in% c("New York", "Rhode Island", "Texas", "Florida")) %>%
  ggplot(aes(year, inf_adj_perchild, color = state)) +
  geom_line() +
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar)
```

to check 4 states in 4 different graphs
```{r}
kids %>% 
  filter(variable == "PK12ed",
         state %in% c("New York", "Rhode Island", "Texas", "Florida")) %>% 
  ggplot(aes(year, inf_adj_perchild)) +
  geom_line()+
  facet_wrap(~ state)
  expand_limits(y = 0)+
  scale_y_continuous(labels = dollar)
```


```{r}
kids %>%
  filter(variable == "PK12ed",
         state %in% sample(unique(state), 30)) %>% # randomly choose 30 unique states
  mutate(state = fct_reorder(state, inf_adj_perchild, .fun = max, .desc = TRUE)) %>% 
  ggplot(aes(year, inf_adj_perchild)) +
  geom_line()+
  facet_wrap(~ state)+
  geom_vline(xintercept = 2009, color = "red", linetype = "dashed") +
  expand_limits(y = 0)+
  scale_y_continuous(labels = dollar)+
  labs(x = "year",
       y = "Inflation-adjusted spending per child")

kids %>% 
  filter(variable == "PK12ed") %>% 
  group_by(state) %>% 
  arrange(state, year) %>% 
  mutate(change = inf_adj_perchild / first(inf_adj_perchild) - 1) %>% #try to calculate the changes
  ggplot(aes(year, change)) +
  geom_line()+
  facet_wrap(~ state)+
  geom_vline(xintercept = 2009, color = "red", linetype = "dashed") +
  scale_y_continuous(breaks = c(0, 1, 2), labels = percent) +
  expand_limits(y = 0)+
  labs(y = "change of Inflation-adjusted spending per child relative to 1997")
```

We can also creat a function to apply to other areas
```{r}
plot_change_faceted <- function(mydata) {
  mydata %>% 
    group_by(state) %>% 
    arrange(state, year) %>% 
    mutate(change = inf_adj_perchild / first(inf_adj_perchild) - 1) %>% #try to calculate the changes
    ggplot(aes(year, change)) +
    geom_line()+
    facet_wrap(~ state)+
    geom_vline(xintercept = 2009, color = "red", linetype = "dashed") +
    scale_y_continuous(breaks = c(0, 1, 2), labels = percent) +
    expand_limits(y = 0)
}

kids %>% 
  filter(variable == "highered") %>%
  plot_change_faceted() +
  labs(y = "change of Inflation-adjusted spending per child relative to 1997",
       title = "How has higher education spending changed per state")
 
```
